#!/usr/bin/env bash

if [ -d world ]; then
    echo "[SYNC] persist begin"
    java -classpath postgresql-42.2.2.jar:. App $1 persist
    echo "[SYNC] persist complete"
else
    echo "[SYNC] restore begin"
    java -classpath postgresql-42.2.2.jar:. App $1 restore
    echo "[SYNC] restore complete"
fi

