#!/usr/bin/env python

DATABASE_URL = "postgres://ckkrpslkgcshwr:7b311ec01d48e53ea34cc4ea1f82948376f12af5cebf7988d84b148cf3e213ef@ec2-54-75-244-248.eu-west-1.compute.amazonaws.com:5432/d1gavg31t0f9th"

import psycopg2

cursor = psycopg2.connect(DATABASE_URL)
